model:
    ### Distant endpoint
#    victim_model: "Qwen/Qwen1.5-7B-Chat"
#    victim_url: "http://134.76.18.30:8084/v1/chat/completions"
#
#    jailbreaker_model: "mlabonne/Meta-Llama-3.1-8B-Instruct-abliterated"
#    jailbreaker_url: "http://134.76.18.30:8083/v1/chat/completions"
#
#    judge_model: "meta-llama/Meta-Llama-Guard-2-8B"
#    judge_api_url: "http://134.76.18.30:8081/v1/chat/completions"

    ### Local endpoint
    victim_model: "llama3.2:1b"
    victim_url: "http://localhost:11434/api/chat"

    jailbreaker_model: "huihui_ai/llama3.2-abliterate:1b"
    jailbreaker_url: "http://localhost:11434/api/chat"

    judge_model: "llama-guard3:1b"
    judge_api_url: "http://localhost:11434/api/generate"
