model:
  # Distant endpoint
  victim_model: "Qwen/Qwen1.5-7B-Chat"
  victim_url: "http://134.76.18.30:8084/v1/chat/completions"

  jailbreaker_model: "mlabonne/Meta-Llama-3.1-8B-Instruct-abliterated"
  jailbreaker_url: "http://134.76.18.30:8083/v1/chat/completions"

  judge_model: "meta-llama/Meta-Llama-Guard-2-8B"
  judge_api_url: "http://134.76.18.30:8081/v1/chat/completions"